name: Azure Pipelines

trigger: none

variables:
- group: Quality_Release_SSH_Info
- name: python.version
  value: '3.7'

pool:
  vmImage: 'ubuntu-16.04'
  
stages:




- stage: Deploy

  jobs:


  - deployment: VMDeploy
    displayName: 'QA for Website'
    environment:
      name: 'QA'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          #- checkout: self

          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: $(KNOWN_HOSTS)
              sshPublicKey: $(aps-tf-public-key)
              sshKeySecureFile: 'id_rsa'
            env:
              KNOWN_HOSTS   : $(aps-known-host)
              PUBLIC_KEY    : $(aps-tf-public-key)

