name: Azure Pipelines

trigger: none

variables:
- group: Quality_Release_SSH_Info
- name: python.version
  value: '3.7'

pool:
  vmImage: 'ubuntu-latest'
  
stages:



- stage: Test
  variables:
  - name: POSTMANSRCDIR
    value: $(Build.SourcesDirectory)/automatedtesting/postman/
  - name: POSTMANREPORTDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/postman/report/
  - name: JMENDURETESTDIR
    value: $(Build.SourcesDirectory)/automatedtesting/jmeter/endurance
  - name: JMENDURETESTREPORTDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/jmeter/endurance/report
  - name: JMENDURETESTINDEXDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/jmeter/endurance/index
  - name: JMESTRESSTESTDIR
    value: $(Build.SourcesDirectory)/automatedtesting/jmeter/stress
  - name: JMSTRESSTESTREPORTDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/jmeter/stress/report
  - name: JMSTRESSTESTINDEXDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/jmeter/stress/index

  jobs:

  - job: PerformQATests

    steps:
    
    - checkout: self

    - task: Bash@3
      displayName: Install JMeter
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get install openjdk-11-jre-headless -y
          java -version
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.2.1.tgz -O jmeter.tgz
          tar xzvf jmeter.tgz
          apache-jmeter-5.2.1/bin/jmeter --version
          pwd
          ls -la
    - task: Bash@3
      displayName: JMeter Stress Test
      inputs:
        targetType: 'inline'
        script: |
          sudo mkdir $(JMSTRESSTESTREPORTDIR)
          echo $(JMSTRESSTESTREPORTDIR)
          rm -rf *.csv $(JMSTRESSTESTREPORTDIR)/*
          echo "Running JMeter tests Now"
          apache-jmeter-5.2.1/bin/jmeter -n -t $(JMESTRESSTESTDIR)/Project_3-Stress-Test_Plan.jmx \
          -l StressTest_Results.csv -e -f -o $(JMSTRESSTESTREPORTDIR)
    - task: Bash@3
      displayName: JMeter Endurance Test
      inputs:
        targetType: 'inline'
        script: |
          sudo mkdir $(JMENDURETESTREPORTDIR)
          rm -rf *.csv $(JMENDURETESTREPORTDIR)/*
          apache-jmeter-5.2.1/bin/jmeter -n -t $(JMENDURETESTDIR)/Project_3-Endurance-Test_Plan.jmx \
          -l EnduranceTest_Results.csv -e -f -o $(JMENDURETESTREPORTDIR)




