name: Azure Pipelines

trigger: none

variables:
- group: Quality_Release_SSH_Info
- name: python.version
  value: '3.7'

pool:
  vmImage: 'ubuntu-latest'
  
stages:



- stage: Test
  variables:
  - name: POSTMANSRCDIR
    value: $(Build.SourcesDirectory)/automatedtesting/postman/
  - name: POSTMANREPORTDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/postman/report/
  - name: JMENDURETESTDIR
    value: $(Build.SourcesDirectory)/automatedtesting/jmeter/endurance
  - name: JMENDURETESTREPORTDIR
    value: $(Build.ArtifactStagingDirectory)/endurancereport
  - name: JMENDURETESTINDEXDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/jmeter/endurance/index
  - name: JMESTRESSTESTDIR
    value: $(Build.SourcesDirectory)/automatedtesting/jmeter/stress
  - name: JMSTRESSTESTREPORTDIR
    value: $(Build.ArtifactStagingDirectory)/stressreport
  - name: JMSTRESSTESTINDEXDIR
    value: $(Build.ArtifactStagingDirectory)/automatedtesting/jmeter/stress/index

  jobs:

  - job: PerformQATests

    steps:
    
    - checkout: self

    - task: Bash@3
      displayName: Install JMeter
      inputs:
        targetType: 'inline'
        script: |
          # sudo apt-get install openjdk-16-jre-headless -y
          java -version
          wget https://mirrors.gigenet.com/apache//jmeter/binaries/apache-jmeter-5.4.1.tgz -O jmeter.tgz
          tar xzvf jmeter.tgz
          apache-jmeter-5.4.1/bin/jmeter --version
          pwd
          ls -la
    - task: Bash@3
      displayName: JMeter Stress Test
      inputs:
        targetType: 'inline'
        script: |
          mkdir stressreport
          echo "Made the directory stressreport"
          rm -rf *.csv stressreport/*
          echo "Running JMeter tests Now"
          apache-jmeter-5.4.1/bin/jmeter -n -t $(JMESTRESSTESTDIR)/Project_3-Stress-Test_Plan.jmx \
          -l stress.csv -e -o stressreport/
          mv stress.csv stressreport
          pwd
          ls -la

    - task: ArchiveFiles@2
      displayName: 'Archive Stress Report'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/stressreport'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-stressreport.zip'
        verbose: true
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-stressreport.zip
      displayName: 'Upload Stress Report Zip'
      artifact: stressreport





