name: Azure Pipelines

trigger: none

variables:
- group: Quality_Release_SSH_Info
- name: python.version
  value: '3.7'

pool:
  vmImage: 'ubuntu-16.04'
  
stages:

- stage: Build

  jobs:

  - job: Build



    steps:
 
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/automatedtesting/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
        verbose: true
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi


- stage: Deploy

  jobs:


  - deployment: VMDeploy
    displayName: 'QA for Website'
    environment:
      name: 'QA'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:

            
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'QASC'
              appType: 'webAppLinux'
              appName: 'Python-Linux-app'
              package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'
              runtimeStack: 'DOTNETCORE|5.0'
              appSettings: '-WEBSITE_RUN_FROM_PACKAGE 0'


